### ISSUE TITLE
project_environment_variable values should be sensitive

### ISSUE THREAD

**Issue by viki53** [vercel/terraform-provider-vercel#71] opened 2022-09-08 16:00 UTC
Hi,

I've started to use your provider earlier today and I'm having a few issues and questions.

My main issue is the difference of behavior between the `vercel_project.environment` block and the `vercel_project_environment_variable` resource: the first one marks all values as sensitive (which is good for security) but the later doesn't so I risk having values being output when I don't want them displayed.

I also find weird having to specify an id is the `vercel_project.environment` blocks, but I won't be using them as I much prefer having dedicated resources anyway.

Also, now that this new `vercel_project_environment_variable` resource exists, not specifying the `environment` property in a `vercel_project` shouldn't cause an update of the resource if I never had it specified before: this makes me think that every time I'll update a project property I risk breaking all my env vars and having to re-import them via the `vercel_project_environment_variable` resources, which I define in different TF runs (kind of like the architecture in #47).

---

Update: I tried applying the changes on my project and it did break all the env vars (including those that were defined in the same run using `vercel_project_environment_variable` resources) as I had feared… I had to re-add all of them.   
**This is not OK for a stable deployment process!**

**Comment by dglsparsons** [comment] 2022-09-09 06:39
Hey @viki53, thanks for raising this. I'll try to address your points one at a time here: 

> My main issue is the difference of behavior between the vercel_project.environment block and the vercel_project_environment_variable resource: the first one marks all values as sensitive (which is good for security) but the later doesn't so I risk having values being output when I don't want them displayed.

That's a good catch - the `project_environment_variable` resource is a recent addition. It looks like the `sensitive` field has been accidentally omitted. I'll add this and ship a new provider version. 

> I also find weird having to specify an id is the vercel_project.environment blocks, but I won't be using them as I much prefer having dedicated resources anyway.

The `id` field is a computed value so not something you need to specify. It's used internally for updates, but hopefully isn't something you need to think about ever. 

> not specifying the environment property in a vercel_project shouldn't cause an update of the resource if I never had it specified before this makes me think that every time I'll update a project property I risk breaking all my env vars and having to re-import them via the vercel_project_environment_variable resources

I'm a bit confused about what you mean here. If you've never specified the `environment` property, why would anything change? Are you able to share a reproduction of the issue you encountered here? 

> Update: I tried applying the changes on my project and it did break all the env vars (including those that were defined in the same run using vercel_project_environment_variable resources) as I had feared… I had to re-add all of them.

I'm sorry you encountered this. If you could share steps to reproduce we'll get it investigated asap! 

> I also have an unrelated question: is there a way to get the generated domain for a specific deployment (using a git_branch or target for example)?

If you are creating deployments through the terraform provider, then the [domains](https://registry.terraform.io/providers/vercel/vercel/latest/docs/resources/deployment#domains) field might be what you are after. 
We had some plans to implement a `vercel_deployment` data source, but haven't prioritised this yet. If it's something you're interested I can bump up the issue. 

I hope this helps and addresses everything!

**Comment by viki53** [comment] 2022-09-09 06:54
Thanks for the quick response @dglsparsons!

> It looks like the sensitive field has been accidentally omitted. I'll add this and ship a new provider version. 

Great, thanks! 


>  If you've never specified the environment property, why would anything change?

I've actually imported an existing project, which already had some environment variables defined (via the web interface). After importing the project, `plan`/`apply` said it needed to remove the `environment` block even though it wasn't in my config and I had some `project_environment_variable` resources defined and imported right beside this `project` resource.

When I did the `apply`, all the environment variables were removed (couldn't see them on your web dashboard) and I had to run a new `apply` to re-create them using `project_environment_variable` resources.

It doesn't seem like it wants to remove them anymore now, but I guess there's a bug with the way the `import` manages things as it retrieves the `environment` block then `plan` removes it.

I figure it should just ignore the change if the `environment` block is not defined in the `project` resource (and defining it to an empty list could allow for a forced removal of all variables).

**Comment by dglsparsons** [comment] 2022-09-09 07:09
Ahh gotcha. Yeah, that sounds like an issue with `import` of a project incorrectly reading environment variables. I'll get that addressed - it sounds especially painful. 

> I figure it should just ignore the change if the environment block is not defined in the project resource (and defining it to an empty list could allow for a forced removal of all variables).

This is exactly how it behaves currently (we tested this very thoroughly!) - import aside :).

**Comment by viki53** [comment] 2022-09-09 07:15
Yep, luckily I had already defined all the critical variables in my config, otherwise I could have lost a lot of time looking for what's missing… at almost 7pm yesterday 😅 

Do you want me to create a new ticket for this specific issue to avoid having it all discussed in one place?

**Comment by dglsparsons** [comment] 2022-09-09 07:16
Phew!

> Do you want me to create a new ticket for this specific issue to avoid having it all discussed in one place?

Nah, all good! PRs are up and I'll get a release out soon :). Again, sorry for the pain here!

**Comment by viki53** [comment] 2022-09-09 07:18
Awesome, great work being so quick to act!

You could teach a thing or two to Heroku's team 😂

**Comment by dglsparsons** [comment] 2022-09-09 08:17
Hey @viki53, these issues should both be fixed in [v0.9.1](https://github.com/vercel/terraform-provider-vercel/releases/tag/v0.9.1). 

Please give it a go, and let me know if you encounter anything else!

**Closed by dglsparsons** 2022-09-09 08:17 UTC

**Comment by viki53** [comment] 2022-09-09 08:26
Awesome, works like a charm! 

<img width="597" alt="image" src="https://user-images.githubusercontent.com/1763364/189306464-603521d1-2d8a-4ddf-a40e-507f77efa918.png">

I've seldom seen such a quick release 😁  🚀
